100.get-started=はじめに
  10.seekdb-overview=seekdbの概要
  50.use-seekdb-with-sdk=SDKで使う
  100.use-seekdb-with-sql=SQLで使う
  200.ai-coding=AIコーディングで使う
200.develop=開発
  10.develop-overview=開発の概要
  50.ai-workflow=AIワークフロー
  100.connect-to-seekdb=seekdbへの接続
    200.use-client-connect-seekdb=クライアント経由での接続
    300.sample-program=サンプルプログラム
      100.java=Java
      200.python=Python
      300.c=C
      400.go=Go
      500.php=PHP
      600.rust=Rust
      700.ruby=Ruby
    400.use-the-database-connection-pool=コネクションプール
  200.design-database-schema=データベーススキーマ設計
    35.multi-model=マルチモデルデータ
      100.json=JSON データ
      200.spatial=空間データ
      300.char-and-text=文字およびテキストデータ
  300.read-and-write-data=データの書き込みと読み取り
    100.write-data=データの書き込み
    200.read-data=データの読み取り
      200.multi-table-join-query=複数テーブルの結合クエリ
      300.use-operators-and-functions-in-query=クエリでの演算子と関数の使用
  400.llm=大規模言語モデルの統合
  500.vector-embedding=ベクトル埋め込み
  600.search=検索
    300.vector-search=ベクトル検索
      200.vector-index=ベクトルインデックス
        300.dense-vector-index=密ベクトルインデックス
        400.sparse-vector-index=疎ベクトルインデックス
  700.ai-function=AI関数サービス
400.guides=ガイド
  400.deploy=seekdbのデプロイ
    500.environment-and-configuration-checks=デプロイ前の準備
    700.server-mode=サーバーモード
  460.upgrade=seekdbのアップグレード
  500.manage=seekdbの管理
    100.configuration-management=設定管理
      200.system-configuration-items=設定項目
      300.system-variable=システム変数
    200.high-availability=高可用性
	200.recyclebin=ごみ箱の管理
    300.security=セキュリティと権限
      200.identification-and-authentication=識別と認証
      300.access-control=アクセス制御
        200.user-and-permission=ユーザーと権限
          200.permission=権限管理
            340.role-management=ロール管理
      400.data-transfer-encryption=データ転送の暗号化
  1000.obshell=運用保守ツールobshell
    300.obshell-clients=obshellコマンド
    350.obshell-dashboard=obshellダッシュボード
  1050.data-load-and-dump=データのインポートとエクスポート
  1100.performance-test=パフォーマンステスト
    100.vectordbbench-test-on-seekdb=seekdb Vectordbbenchテスト
    200.sysbench-test-on-seekdb=seekdb Sysbenchテスト
    300.tpc-h-test-on-seekdb=seekdb TPC-Hテスト
    400.mldr-test-on-seekdb=seekdb MLDRテスト
450.reference=リファレンス
  100.mysql-compatibility=互換性
  200.sql=SQL リファレンス
    100.sql-syntax=SQL 構文
      100.basic-elements=基本要素
        100.data-type=データ型
          200.numeric=数値型
          300.date-and-time-types=日付・時刻型
          400.string=文字列型
          500.large-object=ラージオブジェクトおよびテキスト型
          800.json-formatted-data-type=JSONデータ型
          900.spatial-data-type=空間データ型
          1000.roaring-bitmap-data-type=高効率圧縮ビットマップデータ型
          1200.array-data-type=配列データ型
          1300.map-data-type=マップデータ型
        200.expression=式
        300.character-set-and-collation=文字セットと照合順序
        400.literal=リテラル
      200.operator=演算子
      400.functions=関数
        200.single-row-functions=単一行関数
          100.date-and-time-functions=日付・時刻関数
          200.string-functions=文字列関数
          300.conversion-functions=変換関数
          400.mathematical-functions=数学関数
          500.comparison-functions=比較関数
          600.process-control-functions=フロー制御関数
        300.aggregate-function=集約関数
        400.analysis-functions=分析関数
        500.encryption-and-compression-functions=暗号化・圧縮関数
        600.information-functions=情報関数
        700.json-functions=JSON関数
          100.create-json-text-function=JSONテキストを作成する関数
          200.search-json-text-function=JSONテキストを検索する関数
          300.modify-json-text-function=JSONテキストを変更する関数
          400.return-json-text-property-function=JSONテキストのプロパティを返す関数
          500.json-utility-function=JSONユーティリティ関数
          600.json-aggregate-function=JSON集約関数
          700.json-schema-function=JSON Schema検証関数
        750.xml-functions=XML関数
          300.querying-xmltype-data-functions=XMLデータを照会する関数
          400.modify-xmltype-data-functions=XMLデータを変更する関数
        800.spatial-functions=空間関数
        900.performance-schema=Performance Schema関数
        920.lock-functions=ロック関数
        940.roaring-bitmap-functions=ビットマップ関数
        950.array-functions=配列関数
        960.text-processing-functions=テキスト処理関数
        970.audit-functions=監査関数
        980.map-functions=マップ関数
        990.sequence-function=シーケンス関数
        1000.other-functions=その他の関数
      500.queries-and-subqueries=クエリとサブクエリ
      600.sql-statement=SQL ステートメント
        300.alter-system=ALTER SYSTEM
        8100.select=SELECT
      700.ddl-function=DDL機能
      800.overview-of-pseudo-columns=疑似列
    300.pl=PLリファレンス
      100.what-is-pl=PLとは
      200.storage-object=PLストアドプログラム
      300.cursor=PLカーソル
      400.control-statement=PL条件制御ステートメント
      500.pl-manipulation-statement-mysql=PLデータ操作ステートメント
      600.sql-statements-for-pl-stored-programs=PLデータ定義ステートメント
      700.pl-database-management-statements=PLデータベース管理ステートメント
      800.information-schema-dictionary-view=PL関連のディクショナリビュー
      900.pl-exception-handling-statement=PL例外処理
      1000.pl-system-package=PLシステムパッケージ
        9000.dbms-hybrid-search=DBMS_HYBRID_SEARCH
        9950.dbms-mview=DBMS_MVIEW
        10050.dbms-mview-stat=DBMS_MVIEW_STATS
        13200.dbms_partition=DBMS_PARTITION
        13300.dbms-resource-manager=DBMS_RESOURCE_MANAGER
        15900.dbms-stats=DBMS_STATS
        17800.dbms-udr=DBMS_UDR
        17850.dbms-vector=DBMS_VECTOR
        17900.dbms-workload-repository=DBMS_WORKLOAD_REPOSITORY
  600.error-code=よくあるエラーコード
  700.telemetry=テレメトリ
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      30.sdk-samples=SDK サンプル
      50.apis=API
        110.database=Database
        200.collection=Collection
        300.dml=DML
        400.dql=DQL
      60.embedding-funcations=埋め込み関数
        400.embedding-function-wrapper-py=プラットフォーム統合
    20.seekdb-js=seekdb-js
      30.sdk-samples-of-seekdb-js=SDKサンプル
      50.apis-of-seekdb-js=API
        110.database-of-seekdb-js=Database
        200.collection-of-seekdb-js=Collection
        300.dml-of-seekdb-js=DML
        400.dql-of-seekdb-js=DQL
      60.embedding-funcations-of-seekdb-js=埋め込み関数
        700.embedding-function-wrapper-js=プラットフォーム統合
500.tutorials=チュートリアル
  100.create-ai-app-demo=AIアプリの構築
  200.scenarios=シナリオの実践
600.demos=デモ
